image: ubuntu:18.04

pipelines:
  default:
    - step:
        name: build and check
        script:
          - apt-get update
          - apt-get install -y --no-install-recommends build-essential autoconf git
          - autoreconf --install
          - ./configure
          - make
          - make check
          - make distcheck
  tags:
    '*':
    - step:
        name: build and POST
        script:
          - apt-get update
          - apt-get install -y --no-install-recommends build-essential autoconf git
          - autoreconf --install
          - ./configure
          - make
          - make check
          - make distcheck
          - pipe: atlassian/bitbucket-upload-file:0.3.2
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_REPO_OWNER
              BITBUCKET_APP_PASSWORD: $PIPELINES_APP_PASSWORD
              FILENAME: "*.tar.xz"
